publishDir: "docs"
canonifyurls: true
baseURL: "https://forjobok.github.io/"
languageCode: "jp"
title: "KENTO-Portfolio"
theme: "./.."
relativeURLs: true

googleanalytics: G-G981828089
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: false

  favicon: "/images/maro.png"
  description: "Welcome to my portfolio."

  # home
  disable_home: false
  profile_image: "/images/profile.jpg"
  name: "KENTO ONOUE"
  namecolor: ffc107
  profession: "XR engineer"
  github: "https://github.com/ForJobOk"
  linkedin: "https://www.linkedin.com/in/onouekento/"
  twitter: "https://twitter.com/kento_xr"
  facebook: "https://www.facebook.com/onoue.kento"
  
  # About
  disable_about: false
  descripe_l1_person: "Joined a sales company as a new graduate.
                       It all started with a longing for technology and I changed jobs. I was lucky enough to become a VR engineer.
                       I was engaged in creating VR packages for safety education as a programmer.
                       After that,I turned into an XR engineer to broaden the range of work.
                       As an R&D engineer, I was involved in the validation of new devices and new functions of XR.
                       Currently, I am working on the development of STYLY, which is an XR platform."
  descripe_l2_person: "I have been acting with the main business lines of AR, VR, and a mobile application productions.
                       If you have some opinion or work to request,please feel free to contact me by e-mail."
  skills:
    - name: Unity
      percentage: 90
    - name: C#
      percentage: 85
    - name: VR
      percentage: 90
    - name: AR
      percentage: 80

  # Experience
  disable_experience: false
  experience:
    - company: "Freelance"
      id: "Freelance"
      role: "XR/Metaverse engineer"
      startdate: Apr 2023
      enddate: present
      featuredpoints:
        - point: Independent as a freelance XR/metaverse engineer.
    - company: "Psychic VR Lab"
      id: "PsychicVRLab"
      role: "XR engineer"
      startdate: Oct 2021
      enddate: Mar 2023
      featuredpoints:
        - point: Work as Unity engineer and develop XR platform.
    - company: "Up-frontier"
      id: "Up-frontier"
      role: "XR engineer"
      startdate: Feb 2020
      enddate: Sep 2021
      featuredpoints:
        - point: Research and development about XR.
    - company: "NANO Media"
      id: "NANOMedia"
      role: "VR engineer"
      startdate: Oct 2018
      enddate: Jan 2020
      featuredpoints:
        - point: Develop VR application for safety education.
    - company: "Asahi Soft Drink Sales"
      id: "AsahiSoftDrinkSales"
      role: "Sales"
      startdate: Apr 2017
      enddate: Sep 2018
      featuredpoints:
        - point: Vending machine management and sales.

  # Education
  disable_education: true

  # Achievements
  disable_achievements: true

  # Contact
  disable_contact: true
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "kentou1506@gmail.com"

  # Footer
  socialiconfooter: false
  recentposts: false

  # Blog
  showdescription: false
  tweet: true
